{% set python_min = '3.10.0' %}
{% set name = "pytrms" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytrms-{{ version }}.tar.gz
  sha256: 4ed4bf0c02f8e895f7bcb570bae769d281a53717fef6cb6a757643b9970796eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - h5py >=3.12.1,<4.0.0
    - matplotlib-base >=3.9.2,<4.0.0
    - requests >=2.32.3,<3.0.0
    - pandas >=2.2.3,<3.0.0
    - pymodbustcp >=0.1.9
    - paho-mqtt >=1.6.1,<1.7.0

test:
  imports:
    - pytrms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ionicon-analytik/PyTRMS
  summary: Python bundle for proton-transfer reaction mass-spectrometry (PTR-MS).
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lefi7z
